### ISSUE TITLE
Allow CONTRIBUTING in .github

### ISSUE THREAD

**Issue by GaryJones** [producerphp/producer.producer#1]
With https://github.com/blog/2111-issue-and-pull-request-templates, GitHub also looks for CONTIBUTING[.md] to be found in a `.github` directory. Maybe Producer should also check in there if it can't find it in the package root, so developers can get the best of both tools?

**Comment by pmjones** [comment]
Good call. That'll expand the logic for that particular file a bit, but it seems reasonable. If you want to submit a PR so you get automatic credit, go for it; otherwise, I'll attend to it myself later. Thanks!

**Comment by pmjones** [comment]
This has been added in the 2.x branch. You can now create a package-specific `.producer/config` file with these directives ...

```
[files]
contributing = .github/CONTRIBUTING
```

... and Producer should look there, instead of in `./CONTRIBUTING[.md]`.
