### ISSUE TITLE
Default changelog file should be CHANGELOG.md

### ISSUE THREAD

**Issue by Seldaek** [producerphp/producer.producer#10]
As per https://seld.be/notes/common-files-in-php-packages - CHANGELOG is much more common than CHANGES, so would be nice to have that as default IMO.

Not a huge deal, but after all this trouble (c.f. the post linked), I kinda had to create this issue ;)

**Comment by pmjones** [comment]
LOVE THIS. Thanks man. Let me figure out how big a deal it would be to change the default in a stable release.

**Comment by pmjones** [comment]
(FWIW, I've been using "CHANGES" for years, thus its primacy here.)

**Comment by svpernova09** [comment]
That's awesome :D

**Comment by Seldaek** [comment]
Haha I know how to get to you ;) It's not really urgent to change it, but the file list might inform your defaults going forward. 

Either way if more people have changelogs at all it would be great ;)

**Comment by pmjones** [comment]
So, I have a way to default to CHANGELOG.md without breaking BC. However, the format of http://keepachangelog.com is not amenable to using the entire file contents as a release note for a GitHub release. I'll continue to see what I can do.

**Comment by Seldaek** [comment]
Oh I see, CHANGES contains only the last version's changes. I didn't realize that. That's more than a file name change indeed. Would be cool if it found the right block and posted that to github's release notes though :)

**Comment by pmjones** [comment]
> Would be cool if it found the right block and posted that to github's release notes though :)

Yes, that's what I'm thinking too. The issue is to keep the old `CHANGES.md` behavior _and_ the new `CHANGELOG.md` behavior, so as not to break BC. Give me a few minutes and I'll push a `changelog` branch so you can see the progress, and (AFTER CAUSING ALL THIS TROUBLE ;-) maybe submit a PR in your copious free time.

**Comment by pmjones** [comment]
@Seldaek OK, take a look at the new `changelog` branch, started with this commit https://github.com/producerphp/producer.producer/commit/3ae9c506696ab496eca807746cf66f1c308a315a , and critique at will.

**Comment by Seldaek** [comment]
Seems fine to me so far but I am not extremely familiar with the project.

**Comment by pmjones** [comment]
Using CHANGELOG is now required in the 3.x branch, per the [pds/skeleton](https://github.com/php-pds/skeleton) research.
