### ISSUE TITLE
[Feature Request] Utilise Composer scripts

### ISSUE THREAD

**Issue by raphaelstolt** [producerphp/producer.producer#15]
Would it be possible to move to utilising [Composer scripts](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands) like `composer test`? This would remove the requirement to set an explicit path to PHPUnit, while also opening the possibility to use other testing frameworks (e.g. PHPSpec, Codeception) and also scripting own validation logic (like no code standard violations allowed).

So the config would look more like:

```
[commands]
test-run = composer test
(phpdoc-check = composer doc-check)
```

Possibly the `commands` ini section should be renamed to something like `validation-steps` or the like.

**Comment by pmjones** [comment]
Does `composer test` return a value useful in determining if the tests passed or not, that is always the same regardless of the underlying test system? For example, does `composer test` always `exit (0)` when the tests pass (whether PHPUnit, PHPSpec, etc), and always `exit (1)` when they fail?

**Comment by raphaelstolt** [comment]
Yes it does. Just tested this with a repository of mine.

**Comment by pmjones** [comment]
(/me ponders)

Is the return code a function of `composer test`, or is it a feature of the underlying test system? (I ask only because I don't want Producer to have to deal with special cases for every possible testing system.)

Overall I like the idea, but it's probably a BC break of some sort. If so, that would make it 3.x feature. It might go well with the #10, especially if I cannot shoehorn that into 2.x without a BC break.

(Given that the duration between 1.x and 2.x was about four weeks, a 3.x might come about in a timely way.)

**Comment by raphaelstolt** [comment]
Don't now the internals of how Composer scripts work, maybe we should ping @Seldaek for this one. I think it's also set that every testing framework will return `0` on successfull test runs and `1` for failing test runs, otherwise they wouldn't work in a CI environment.

It would be defo a BC break. My motiviation for this feature would be to integrate it into [Construct](https://github.com/jonathantorres/construct) which utilises Composer scripts.

**Comment by pmjones** [comment]
> It would be defo a BC break.

Yeah, agreed. I have created a 3.x branch; feel free to make PRs against it. I cannot promise a particular timeline or schedule, though.

**Comment by Seldaek** [comment]
If a script exits with non-zero, we also do, so it should be reliable.

**Comment by pmjones** [comment]
@raphaelstolt Actually, in a 2.x version, can you try setting the config value `phpunit = composer test` ? It might actually work as it is right now.

**Comment by pmjones** [comment]
@raphaelstolt I just tried this in Producer 2.x, and it works. If you have a `"scripts": {"test": "phpunit"}` entry in `composer.json`, you can set the relevant `.producer/config` entry as `phpunit = composer test`. That means `composer test` can run anything at all (PHPSpec, Behat, etc). The only sticking point is that the `.producer/config` entry key is still `phpunit`, which sucks; I can rename that key in a 3.x release.
