### ISSUE TITLE
[Feature Request] Let Producer work with self-hosted GitLab instance

### ISSUE THREAD

**Issue by shochdoerfer** [producerphp/producer.producer#16]
As far as I can see from the current code, I am not able to hook producer up with a self-hosted GitLab instance. The current code assumes that the API endpoint is always gitlab.com.

Would love to contribute the needed changes in case you think it makes sense ;)

**Comment by pmjones** [comment]
Please! I think the GitHub Enterprise work in #13 might be a good place to start.

**Comment by shochdoerfer** [comment]
Will wait then till #13 is finalized / merged and then go from there.

**Comment by pmjones** [comment]
Or combine efforts; my guess is that the two will have similar solutions. As you see fit!

**Comment by mdwheele** [comment]
I will go ahead and implement the configuration for Gitlab and we can discuss from there. The idea will be the same; ability to specify user-level configuration as well as per-project override of that configuration.

**Comment by pmjones** [comment]
I believe this has been accomplished as part of #13 . Let me know if not!

**Comment by shochdoerfer** [comment]
All good. Nothing to complain (yet) :)
