### ISSUE TITLE
Feedback regarding .producer/config per repo.

### ISSUE THREAD

**Issue by svpernova09** [producerphp/producer.producer#17]
I'm really excited that development has been moving forward so quickly with Producer. Even more excited about seeing different people contributing code and ideas / feedback.

I really like the idea of a producer config file (Currently implemented as `.producer/config` as of the 2.0 release. My only feedback here is wouldn't it be more inline with other services to have the producer specific config options in a `.producer.{$ext}` file? I don't really what `$ext` is, but feel like not having the `.producer/` folder in my library/repo/package would be cleaner.

**Comment by pmjones** [comment]
Hey Joe -- thanks for writing. :-)

Believe it or not, very early versions used just a `.producer` file (no extension). However, I began to imagine that other support files would be needed at some point, perhaps templates of some sort, which means that the directory will become useful. So I get you on the "just a file would be cleaner" bit, but I think having the space available "just in case" is worth the tradeoff.

Happy to hear your response; perhaps I have missed a better alternative.

**Comment by svpernova09** [comment]
Thanks for the quick reply.

The folder certainly isn't a dealbreaker for me. I think it may just be a mild OCD flare up. My primary use case is to bring the many repos [Phergie](https://github.com/phergie) has to a consistent point. 

Here is one of our repos utilizing the folder: https://github.com/phergie/phergie-irc-plugin-react-commandhelp. Very minimal impact IMHO.

Here is another repo where we're utilizing a number of services/tools: https://github.com/phergie/phergie-irc-bot-react

Adding `.producer/config` here is where I see a bit of a mess come in. (Granted this is all self inflicted). We're using Codeclimate, Coveralls, PHP Code Sniffer, Travis CI, and Editorconfig all for specific reasons. IMHO I'd rather have yet-another-dot-file as a config. 

I see the value of the trade off in being able to dump other files into `~/.producer`. Would supporting both be too cumbersome? I figure it might be versus the folder not being a huge deal for me.

**Comment by pmjones** [comment]
Supporting both might not be too cumbersome. There are other PRs (or works-in-progress) that make allowance for alternatives on other features.

Tell you what: if you have the time and inclination, send a PR that looks for `.producer/config` first, then `.producer` after that, and I'll review it.

**Comment by svpernova09** [comment]
Cool. I'm planning on showing off Producer tomorrow in front of a live MemphisPHP audience. I'll see what kind of feedback they have regarding the config.

**Comment by pmjones** [comment]
Sweeeet. Let me know how it goes!

**Comment by svpernova09** [comment]
Demo for MemphisPHP went well last night. I goofed and misspoke about how the check changes works, but other than that pleased with the demo. No one else thought the `.producer` config folder would be a problem so closing this. Thanks for the responses!

Video here if interested: https://www.youtube.com/watch?v=gEBfxstZR44

**Comment by pmjones** [comment]
Watched the demo -- very nice! Thanks for doing it.

FWIW, "check changes" looks at the latest log timestamp for "CHANGES.md" and the latest log timestamp for the repo as a whole. If they are not the same, Producer figures there are unrecorded changes.

Also, watching this, it occurs to me that the "admin files" stuff probably ought to come at the end, and the "CHANGES.md is present and non-empty" check should be the absolute last, so you don't have to keep updating it with every little change.

Thanks again for running the demo!
