### ISSUE TITLE
[Feature Request] Allow for vagrant to be used in tests

### ISSUE THREAD

**Issue by electricjones** [producerphp/producer.producer#4]
Vagrant and disposable dev environments are becoming more prominent, and I believe for good reason. I am the maintainer of [Spider](http://github.com/spider/spider) which uses vagrant. The tests cannot pass without that environment, so Producer cannot be used to its fullest.

I would propose abstracting away the command in `checkTests()` to allow for a custom command to be set in the configuration, if desired.

Thoughts? If I get some time today, I may scratch together a PR.

**Comment by pmjones** [comment]
Agreed. I'd like to re-purpose your suggestion a bit, if I may. It's on the TODO to have Producer look at a repo-specific ".projector" file for overrides, etc. Would you like to take that on? I can easily see a  "tests" command (or the like) configured via that .projector file. Thoughts?

**Comment by pmjones** [comment]
Oh, and if you do a PR, please base it against the 2.x branch.

**Comment by svpernova09** [comment]
Would love to see a way to override PHPUnit to allow something like phpspec / behat / codeception to be used.

**Comment by electricjones** [comment]
Yeah. that sounds great. I'll get to it after lunch. If you would like to rename this issue, you are welcome to.

**Comment by electricjones** [comment]
I had a couple quick questions about the project specific config:
- [ ] Once the repo-specific `.producer` file is loaded, would you like those values appended to the `Config` object? Should they be namespaced, say `config.overwrites`?
- [ ] I assume you would like that file to be in ini format.
- [ ] While I'm at it, are there any other project-specific configs you'd like placed? Any defaults with those?

**Comment by pmjones** [comment]
Yes, put them in the Config object. My first intuition is that they should replace any default values, and not be namespaced.

Yes, ini format.

The only other project-specific config I had in mind was for `@package` tags. The default is the Composer package name, but I can see where someone might want to override that.

Thanks!

**Comment by chrismichaels84** [comment]
Is there a reason that the config file is parsed twice?

https://github.com/producerphp/producer.producer/blob/2.x/src/Repo/AbstractRepo.php#L82

and

https://github.com/producerphp/producer.producer/blob/2.x/src/Config.php#L52

Would it be alright if we passed in the already parsed `Config` item into the `newRepo` method in `ProducerContainer`?

**Comment by chrismichaels84** [comment]
My apologies. I should have just looked closer :)

**Comment by electricjones** [comment]
I've opened PR #5 which covers both of these in two commits.

**Comment by pmjones** [comment]
I believe your PR, and my subsequent changes, fix this issue. Let me know if you need to reopen!
