### ISSUE TITLE
[Feature Request] Support Sami

### ISSUE THREAD

**Issue by kix** [producerphp/producer.producer#6]
It would be nice if [Sami](https://github.com/FriendsOfPHP/Sami) would be supported by Producer.

**Comment by pmjones** [comment]
Does Sami generate a report on what docblocks, and parts of docblocks, are missing?

**Comment by kix** [comment]
@pmjones, not sure about that, should be easy to implement if it isn't able to do that yet. 
Also, if missing docblock report is the only reason you need PHPDocumentor as a dependency, then would it be possible to use something less complicated? I've had some problems trying to install `Producer@1.x` due to the fact that PHPDocumentor has quite a vast dependency list.

**Comment by kix** [comment]
Hm, looks like my problem here was caused by something else. So this seems irrelevant now.
