### ISSUE TITLE
[Enh] configurable `src/` folder

### ISSUE THREAD

**Issue by Faryshta** [producerphp/producer.producer#7]
I think producer should read the `composer.json` file to readh the `autoload` property and use that to determine which folder(s) to use for executing phpDoc.

**Comment by pmjones** [comment]
/me nods

Reading "autoload" might be a bit tricky; I can see there maybe being more than one autoload entry. Perhaps instead, a "src" config directive in the .producer/config file?

**Comment by Faryshta** [comment]
but wouldn't that mean that you have to configure your project twice? one for composer and one for producer. I am ok with it but I don't see any advantage and probably will cause headaches when you update one file and forget to update another.

>  I can see there maybe being more than one autoload entry. 

Yes, thats the point :smiley: right now if my project has two different folder being autoloaded producer has no way to determine them.

**Comment by pmjones** [comment]
> right now if my project has two different folder being autoloaded producer has no way to determine them.

You're doing that yourself now?  OK then. Send a PR for it, if you have the time and inclination, and I can review.

**Comment by Faryshta** [comment]
Cool let me dip into the code.

**Comment by pmjones** [comment]
On further consideration, given that ["58% of packages include a src/ directory and 5% a lib/ one"](https://seld.be/notes/common-files-in-php-packages), I think making this configurable is not really necessary.
